---
# This playbook contains common plays that will be run on all nodes.

- name: Add group "zap"
  group:
    name="{{zap_group}}"
  tags: zap_setup

- name: Add user "zap"
  user:
    name="{{zap_owner}}"
    group="{{zap_group}}"
    home="{{zap_base_dir}}"
    shell="{{zap_shell}}"
    comment="Zap User"
    createhome=yes
  tags: zap_setup

- name: Create temporary directory
  shell: mktemp -d
  register: tempdir
  sudo: true
  tags: zap_setup

- name: Download zap
  get_url:
    url="{{zap_url}}"
    dest="{{ tempdir.stdout }}/{{zap_archive}}"
  register: zap_download    
  tags: zap_setup
  
- name: Create base directory
  file:
    dest="{{zap_base_dir}}/{{zap_name}}"
    state=directory
    owner="{{zap_owner}}"
    group="{{zap_group}}"
  when: zap_download.changed    
  tags: zap_setup

- name: Extract archive zap
  command: tar xzf {{ tempdir.stdout }}/{{zap_archive}} -C {{zap_base_dir}}/{{zap_name}} --strip-components=1
  when: zap_download.changed

#- name: Extract archive zap
#  unarchive:
#    src="{{ tempdir.stdout }}/{{zap_archive}}"
#    dest="{{zap_base_dir}}"
#    owner="{{zap_owner}}"
#    group="{{zap_group}}"
#    copy=no
#  sudo_user: "{{zap_owner}}"
#  tags: zap_setup

- name: Change archive zap ownership
  file: path={{zap_base_dir}}/{{zap_name}} owner={{zap_owner}} group={{zap_group}} state=directory recurse=yes
  when: zap_download.changed

- name: Stat {{zap_base_dir}}/{{zap_name}}
  stat: path={{zap_base_dir}}/{{zap_name}}
  register: zap_archive_extracted_present

- debug: msg="Path exists and is a directory"
  when: zap_archive_extracted_present.stat.isdir is defined and zap_archive_extracted_present.stat.isdir == true

- fail: msg="Whoops! file ownership has changed"
  when: zap_archive_extracted_present.stat.pw_name != '{{zap_owner}}'

#- name: create a link to zap
#  file:
#    src="{{zap_base_dir}}/{{zap_archive_extracted}}"
#    dest="{{zap_base_dir}}/zap-{{zap_major}}"
#    state=link
#    owner="{{zap_owner}}"
#    group="{{zap_group}}"
#  tags: zap_setup
  
- name: Create a link to zap
  file:
    src="{{zap_base_dir}}/{{zap_name}}"
    dest="{{zap_base_dir}}/zap-{{zap_major}}"
    state=link
    owner="{{zap_owner}}"
    group="{{zap_group}}"
  tags: zap_setup
  
- name: Cleanup temporary directory
  file: name={{ tempdir.stdout }} state=absent
  tags: zap_setup

- debug: msg="Start zap {{zap_base_dir}}/zap-{{zap_major}}/zap.sh"
