---
- name: restart zap 
  service: 
     name=zap
     state=restarted
     enabled={{zap_service_enabled}}
  notify:  wait for zap to start

#- name: wait for zap to start
#  wait_for: 
#     port={{zap_port}}
#     timeout=180
