# {{ ansible_managed }}
#FROM        debian:jessie
#FROM        stackbrew/ubuntu:14.04
FROM        jasongiedymin/ansible-base-ubuntu

# Volume can be accessed outside of container
VOLUME      [{{ docker_volume_directory }}]

MAINTAINER  Alban Andrieu "https://github.com/AlbanAndrieu"

ENV			DEBIAN_FRONTEND noninteractive
ENV         JENKINS_HOME {{ zap_home_dir }}

# Working dir
WORKDIR {{ docker_working_directory }}

# COPY
#COPY

# ADD
ADD defaults $WORKDIR/defaults
ADD meta $WORKDIR/meta
#ADD files $WORKDIR/files
ADD handlers $WORKDIR/handlers
ADD tasks $WORKDIR/tasks
ADD templates $WORKDIR/templates
#ADD vars $WORKDIR/vars

# Here we continue to use add because
# there are a limited number of RUNs
# allowed.
ADD hosts /etc/ansible/hosts
ADD playbook.yml $WORKDIR/playbook.yml -vvvv

# Execute
RUN         ansible-playbook $WORKDIR/playbook.yml -i $WORKDIR/hosts -c local

#RUN         apt-get update && \
#            apt-get install -y openssh-server openjdk-7-jre-headless
#RUN         useradd -m -s /bin/bash jenkins
#RUN         echo jenkins:jenkins | chpasswd
#RUN         mkdir -p /var/run/sshd
            
EXPOSE      22
ENTRYPOINT  ["{{zap_base_dir}}/zap{{zap_major}}/zap.sh"]
CMD /usr/sbin/sshd -D
#CMD ["-g", "deamon off;"]
